# Generated by Django 4.0.6 on 2022-08-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_course_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
